### ISSUE TITLE
Improvements for filtering data

### ISSUE THREAD

**Issue by Guilhem7** [dongit-org/python-reporter#16]
Hi !
First of all thanks for the **client api** you have made !

I was thinking maybe it would be great if we could add more **filter** during search.
For instance:
 - When searching for a finding template, I did not find a way to filter using the `prefer_language`.

Perhaps allowing the user to add extra args to `query_data` would be a solution, but not sure that this is the best solution nor the more efficient.

Thanks !

**Comment by bjhijmans** [comment]
Hi @Guilhem7,

Thank you for using Python Reporter!

You're right, there isn't a way to pass prefer_language currently. I pushed a fix for it to a new branch. Unfortunately, it looks like our github pipeline isn't working. If you can find a way to use the branch of the PR https://github.com/dongit-org/python-reporter/pull/17 you should be able to add additional query parameters to all get requests, including search.

We'll work on fixing the pipelines and we plan on updating this package in the near future with additional routes etc.

**Comment by Guilhem7** [comment]
Thanks for the fast answer and the **PR**, updating today :+1:
